
version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Update APT to install dependencies
          command: sudo apt update
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Backend Unit Tests
          command: python -m unittest discover -s test/backend -p "test_*.py"

workflows:
  build:
    jobs:
      - build-and-test